// Token: 0x02000011 RID: 17
public enum ClientServerMessageFlags
{
    SMSG_KEY = 1,
    CMSG_KEY = 2,
    CMSG_AUTH = 3,
    SMSG_AUTH_STATUS = 4,
    SMSG_BROADCAST = 6,
    CMSG_WARDEN_UPLOAD = 12,
    SMSG_WARDEN_UPLOAD_RSP = 13,
    CMSG_REQUEST_NEEDLE_PAYLOAD = 16,
    SMSG_NEEDLE_PAYLOAD = 17,
    CMSG_REQUEST_OFFSETS = 18,
    SMSG_OFFSETS = 19,
    CMSG_REQEUEST_APAYLOAD = 20,
    SMSG_APAYLOAD = 21,
    CMSG_UPLOAD_GAMEMODULE = 22,
    SMSG_REQUES_GAMEMODULE = 23,
    CMSG_REQUEST_SCRIPTS = 24,
    SMSG_SCRIPTS = 25,
    CMSG_DOWNLOAD_SCRIPT_REQUEST = 26,
    SMSG_DOWNLOAD_SCRIPT = 27,
    CMSG_REQUEST_HOOK_PAYLOAD = 28,
    SMSG_HOOK_PAYLOAD = 29,
    CMSG_REQUEST_TOOL_OFFSETS = 30,
    SMSG_TOOL_OFFSETS = 31
}
