public enum ThreadAccessFlags
{
    TERMINATE = 1,
    SUSPEND_RESUME,
    GET_CONTEXT = 8,
    SET_CONTEXT = 16,
    SET_INFORMATION = 32,
    QUERY_INFORMATION = 64,
    SET_THREAD_TOKEN = 128,
    IMPERSONATE = 256,
    DIRECT_IMPERSONATION = 512,
    THREAD_HIJACK = 26,
    THREAD_ALL = 1019
}
