public enum MemoryProtectionFlags : uint
{
    PAGE_EXECUTE = 16U,
    PAGE_EXECUTE_READ = 32U,
    PAGE_EXECUTE_READWRITE = 64U,
    PAGE_EXECUTE_WRITECOPY = 128U,
    PAGE_NOACCESS = 1U,
    PAGE_READONLY,
    PAGE_READWRITE = 4U,
    PAGE_WRITECOPY = 8U,
    PAGE_TARGETS_INVALID = 1073741824U,
    PAGE_TARGETS_NO_UPDATE = 1073741824U,
    PAGE_GUARD = 256U,
    PAGE_NOCACHE = 512U,
    PAGE_WRITECOMBINE = 1024U
}
