// Token: 0x02000011 RID: 17
public enum ClientServerMessageFlags
{
    SMSG_KEY = 1,
    CMSG_KEY,
    CMSG_AUTH,
    SMSG_AUTH_STATUS,
    SMSG_BROADCAST = 6,
    CMSG_WARDEN_UPLOAD = 12,
    SMSG_WARDEN_UPLOAD_RSP,
    CMSG_REQUEST_NEEDLE_PAYLOAD = 16,
    SMSG_NEEDLE_PAYLOAD,
    CMSG_REQUEST_OFFSETS,
    SMSG_OFFSETS,
    CMSG_REQEUEST_APAYLOAD,
    SMSG_APAYLOAD,
    CMSG_UPLOAD_GAMEMODULE,
    SMSG_REQUES_GAMEMODULE,
    CMSG_REQUEST_SCRIPTS,
    SMSG_SCRIPTS,
    CMSG_DOWNLOAD_SCRIPT_REQUEST,
    SMSG_DOWNLOAD_SCRIPT,
    CMSG_REQUEST_HOOK_PAYLOAD,
    SMSG_HOOK_PAYLOAD,
    CMSG_REQUEST_TOOL_OFFSETS,
    SMSG_TOOL_OFFSETS
}
